### PR TITLE
Add Dockerfile based on Ubuntu

### PR DESCRIPTION
**Pull request by Kikobeats**
Hello!

Based on the Debian image, I did some changes to make it compatible with Ubuntu distribution 🙂

### CODE REVIEW

**Comment by dooman87** [comment]
Thanks a lot for the contibution @Kikobeats! If you could also update README and Github workflow that would be awesome. If you don't have time that's alright - let me know and I'm happy to do that.

**Comment by Kikobeats** [comment]
@dooman87 I did my best, can you review the last commit? 🙂

**Comment by Kikobeats** [comment]
@dooman87 I'm using this Docker image in one of my project but unfortunately BMP detection is failing

https://github.com/microlinkhq/splashy/runs/4091761236?check_suite_focus=true#step:5:19

is there something I can do? maybe a lib dependency is missing in the original image? 🤔

**Comment by Kikobeats** [comment]
In case you are interested, I found some warnings over the build step.

Related to build `libwebp`:

```
make[1]: Entering directory '/libwebp/examples'
  CC       dwebp-dwebp.o
  CC       example_util.lo
  CCLD     libexample_util.la
  CCLD     dwebp
  CC       cwebp-cwebp.o
  CCLD     cwebp
/usr/bin/ld: warning: libwebp.so.6, needed by /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtiff.so, may conflict with libwebp.so.7
  CC       img2webp-img2webp.o
  CCLD     img2webp
/usr/bin/ld: warning: libwebp.so.6, needed by /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtiff.so, may conflict with libwebp.so.7
```

Related to build `ImageMagick`:

```
configure: WARNING: unrecognized options: --with-libtiff
```

**Comment by dooman87** [comment]
> In case you are interested, I found some warnings over the build step.
> 
> Related to build `libwebp`:
> 
> ```
> make[1]: Entering directory '/libwebp/examples'
>   CC       dwebp-dwebp.o
>   CC       example_util.lo
>   CCLD     libexample_util.la
>   CCLD     dwebp
>   CC       cwebp-cwebp.o
>   CCLD     cwebp
> /usr/bin/ld: warning: libwebp.so.6, needed by /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtiff.so, may conflict with libwebp.so.7
>   CC       img2webp-img2webp.o
>   CCLD     img2webp
> /usr/bin/ld: warning: libwebp.so.6, needed by /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtiff.so, may conflict with libwebp.so.7
> ```
> 
> Related to build `ImageMagick`:
> 
> ```
> configure: WARNING: unrecognized options: --with-libtiff
> ```

I saw `libwebp` and I'm not sure what would be the best way to fix it. `--with-libtiff` should be `--with-tiff`, thanks for finding that one!

**Comment by dooman87** [comment]
> @dooman87 I'm using this Docker image in one of my project but unfortunately BMP detection is failing
> 
> https://github.com/microlinkhq/splashy/runs/4091761236?check_suite_focus=true#step:5:19
> 
> is there something I can do? maybe a lib dependency is missing in the original image? thinking

Hmmm...the list of format show that it's there:

```
dimka@dimkaxps:~/Projects/pixboost/ImageMagick$ docker run -it --rm --entrypoint=/bin/bash  dpokidov/imagemagick
root@7297d848aec3:/# magick identify -list format | grep BPM
root@7297d848aec3:/# magick identify -list format | grep BMP
      BMP* rw-   Microsoft Windows bitmap image
     BMP2* rw-   Microsoft Windows bitmap image (V2)
     BMP3* rw-   Microsoft Windows bitmap image (V3)
     WBMP* rw-   Wireless Bitmap (level 0) image
root@7297d848aec3:/# 
```

I've also double checked and BPM supported natively.

**Comment by Kikobeats** [comment]
@dooman87 

Replaced `--with-libtiff` to `--with-tiff` for Ubuntu and Buster images!

You're right about the BMP thing; I double-checked as well, so not sure what's happening

**Comment by dooman87** [comment]
> @dooman87
> 
> Replace `--with-libtiff` to `--with-tiff` for Ubuntu and Buster images!
> 
> You're right about the BMP thing; I double-checked as well, so not sure what's happening

Awesome, thanks a lot for fixing that! There is just one small comment left on image tags. Once done - we can merge it.

**Comment by dooman87** [comment]
Merged, thanks @Kikobeats for your contribution!

**Pull request merged**
